# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\crawler_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver
from selenium.webdriver.common.by import By
from events import *
import sys
class Ui_MainWindow(object):
    def setupUi(self, MainWindow, browser: webdriver.Chrome, iterr, df):
        MainWindow.setObjectName("MainWindow")
        self.browser = browser
        self.iterr = iterr
        MainWindow.resize(279, 272)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.captchaBox = QtWidgets.QLineEdit(self.centralwidget)
        self.captchaBox.setGeometry(QtCore.QRect(10, 170, 151, 31))
        self.captchaBox.setObjectName("captchaBox")
        self.countLabel = QtWidgets.QLabel(self.centralwidget)
        self.countLabel.setGeometry(QtCore.QRect(214, 10, 61, 21))
        self.countLabel.setObjectName("countLabel")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(10, 10, 181, 21))
        self.nameLabel.setObjectName("nameLabel")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(180, 240, 93, 28))
        self.stopButton.setObjectName("stopButton")
        self.passButton = QtWidgets.QPushButton(self.centralwidget)
        self.passButton.setGeometry(QtCore.QRect(180, 210, 93, 28))
        self.passButton.setObjectName("passButton")
        self.surnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.surnameLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.surnameLabel.setObjectName("surnameLabel")
        self.captchaView = QtWidgets.QLabel(self.centralwidget)
        self.captchaView.setGeometry(QtCore.QRect(10, 90, 151, 51))
        self.captchaView.setObjectName("captchaView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.captchatext = False
        self.retranslateUi(MainWindow)
        self.captchaBox.returnPressed.connect(lambda: self.captchaCatcher())
        self.idx = 0
        self.df = df
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def captchaCatcher(self):
        # print(self.captchaBox.text())
        self.browser.find_element(by= By.CSS_SELECTOR, value="#GUVENLIKKODU").send_keys(self.captchaBox.text())
        self.captchaBox.clear()
        self.browser.find_element(by= By.CSS_SELECTOR, value=".buton").click()
        getYuzdelik(self, self.browser, self.idx, self.df)
        self.idx = loopThrough(self, self.browser, self.iterr, self.df)
        if self.idx == -1:
            sys.exit()

        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.countLabel.setText(_translate("MainWindow", "TextLabel"))
        self.nameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.stopButton.setText(_translate("MainWindow", "Durdur"))
        self.passButton.setText(_translate("MainWindow", "Geç"))
        self.surnameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.captchaView.setText(_translate("MainWindow", "TextLabel"))
